[package]
name = "yaml_struct_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
yaml_macro_proc = { path = "yaml_macro_proc"}

